// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = "https://xjffukdtclmcnrzdfvtu.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqZmZ1a2R0Y2xtY25yemRmdnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDg0OTksImV4cCI6MjA3MDkyNDQ5OX0.SDByuJnNckdawgPYmp_BqZ_WVrMMMJtFqUF9wul5_eM";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });